# Generated by Django 5.2.4 on 2025-07-11 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculty", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dean",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appointed_date", models.DateField()),
                ("term_end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("responsibilities", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.department",
                    ),
                ),
                (
                    "faculty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faculty.faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dean",
                "verbose_name_plural": "Deans",
            },
        ),
        migrations.CreateModel(
            name="DeanshipDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("policy", "Policy Decision"),
                            ("academic", "Academic Decision"),
                            ("disciplinary", "Disciplinary Action"),
                            ("budget", "Budget Decision"),
                            ("faculty_hiring", "Faculty Hiring"),
                            ("course_approval", "Course Approval"),
                            ("student_appeal", "Student Appeal"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("decision_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("under_review", "Under Review"),
                            ("implemented", "Implemented"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("implementation_date", models.DateTimeField(blank=True, null=True)),
                ("affected_parties", models.TextField(blank=True)),
                (
                    "budget_impact",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "documents",
                    models.FileField(
                        blank=True, null=True, upload_to="deanship/decisions/"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dean",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="deanship.dean"
                    ),
                ),
            ],
            options={
                "verbose_name": "Deanship Decision",
                "verbose_name_plural": "Deanship Decisions",
                "ordering": ["-decision_date"],
            },
        ),
        migrations.CreateModel(
            name="DeanshipMeeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("department", "Department Meeting"),
                            ("faculty", "Faculty Meeting"),
                            ("academic_council", "Academic Council"),
                            ("administrative", "Administrative Meeting"),
                            ("disciplinary", "Disciplinary Committee"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("meeting_date", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                ("agenda", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("minutes", models.TextField(blank=True)),
                ("action_items", models.TextField(blank=True)),
                (
                    "documents",
                    models.FileField(
                        blank=True, null=True, upload_to="deanship/meetings/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendees",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "dean",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="deanship.dean"
                    ),
                ),
            ],
            options={
                "verbose_name": "Deanship Meeting",
                "verbose_name_plural": "Deanship Meetings",
                "ordering": ["-meeting_date"],
            },
        ),
        migrations.CreateModel(
            name="DeanshipReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly Report"),
                            ("quarterly", "Quarterly Report"),
                            ("annual", "Annual Report"),
                            ("special", "Special Report"),
                            ("performance", "Performance Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("report_period", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("statistics", models.JSONField(blank=True, default=dict)),
                ("achievements", models.TextField(blank=True)),
                ("challenges", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "attachments",
                    models.FileField(
                        blank=True, null=True, upload_to="deanship/reports/"
                    ),
                ),
                ("submitted_to", models.CharField(blank=True, max_length=200)),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dean",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="deanship.dean"
                    ),
                ),
            ],
            options={
                "verbose_name": "Deanship Report",
                "verbose_name_plural": "Deanship Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("operational", "Operational Budget"),
                            ("capital", "Capital Expenditure"),
                            ("research", "Research Budget"),
                            ("infrastructure", "Infrastructure Budget"),
                            ("staff", "Staff Budget"),
                            ("student_activities", "Student Activities Budget"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fiscal_year", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("under_review", "Under Review"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("justification", models.TextField()),
                (
                    "supporting_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="deanship/budgets/"
                    ),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dean",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="deanship.dean"
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Budget",
                "verbose_name_plural": "Department Budgets",
                "ordering": ["-fiscal_year"],
            },
        ),
    ]
