# Generated by Django 5.2.4 on 2025-07-11 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculty", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_code", models.CharField(max_length=20, unique=True)),
                ("course_name", models.CharField(max_length=200)),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("core", "Core Course"),
                            ("elective", "Elective Course"),
                            ("laboratory", "Laboratory Course"),
                            ("seminar", "Seminar"),
                            ("project", "Project"),
                            ("internship", "Internship"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credit_hours", models.IntegerField()),
                ("contact_hours", models.IntegerField()),
                ("description", models.TextField()),
                ("syllabus", models.TextField(blank=True)),
                ("learning_objectives", models.TextField(blank=True)),
                ("assessment_methods", models.TextField(blank=True)),
                ("textbooks", models.TextField(blank=True)),
                ("reference_books", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.department",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(blank=True, to="courses.course"),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["course_code"],
            },
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("fall", "Fall"),
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField()),
                ("section", models.CharField(max_length=10)),
                ("max_enrollment", models.IntegerField()),
                ("current_enrollment", models.IntegerField(default=0)),
                ("classroom", models.CharField(blank=True, max_length=50)),
                ("schedule", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faculty.faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Offering",
                "verbose_name_plural": "Course Offerings",
                "unique_together": {("course", "semester", "year", "section")},
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("homework", "Homework"),
                            ("quiz", "Quiz"),
                            ("midterm", "Midterm Exam"),
                            ("final", "Final Exam"),
                            ("project", "Project"),
                            ("presentation", "Presentation"),
                            ("lab", "Lab Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_marks", models.IntegerField()),
                (
                    "weight_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("due_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courseoffering",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
            },
        ),
        migrations.CreateModel(
            name="StudentAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                (
                    "submission_file",
                    models.FileField(blank=True, null=True, upload_to="assignments/"),
                ),
                ("submission_text", models.TextField(blank=True)),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("late", "Late Submission"),
                            ("missing", "Missing"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("graded_on", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.assignment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Assignment",
                "verbose_name_plural": "Student Assignments",
                "unique_together": {("student", "assignment")},
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enrollment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("dropped", "Dropped"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("final_grade", models.CharField(blank=True, max_length=5)),
                (
                    "grade_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "course_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courseoffering",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Enrollment",
                "verbose_name_plural": "Student Enrollments",
                "unique_together": {("student", "course_offering")},
            },
        ),
    ]
